fix bug IllegalArgumentException
java.lang.RuntimeException: Unable to start activity
ComponentInfo{test.demo.gyniu.v2ex/test.demo.gyniu.v2ex.TopicActivity}:
    java.lang.IllegalArgumentException: missing event subscriber for an
    annotated method. Is
    test.demo.gyniu.v2ex.BaseActivity$Wrapper@eac0352 registered?

add log

Signed-off-by: gyniu <ngyzqf@163.com>